sweep:
  enabled: true
  configuration:
    method: "grid"  # bayes
    metric:
      goal: "minimize"
      name: "loss"
    parameters:
      nonlin:
        values: ["siren"]
      matter:
        values: ["83_new"]
      gene_order:
        values: ["se"]
      lr:
        values: [1e-4]
      hidden_layers:
        values: [6, 8, 10]
      hidden_features:
        values: [512]
      total_steps:
        values: [3000]
      encoding_dim:
        values: [11]
      donor:
        values: ["9861", "10021"]
        # values: ["9861", "10021", "12876", "14380", "15496", "15697"]
  project: "donor_9861_siren"